# Setup
title: George Ho
tagline: "Problem Solver"
url: https://georgehwho.github.io
# paginate: 1
baseurl: ""
permalink: pretty

# pages in nav bar
include: ['_pages']
pages_list:
  About: '/about'
  Archive: '/archive'

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: George Ho
  url: https://twitter.com/GeorgeHo123
  email: george.h.w.ho@gmail.com

# Custom vars
version: 3.0.0
